### PR TITLE
Create dom.txt

### PR DESCRIPTION
**Pull request by ARAVIND472A**
please review my code

### CODE REVIEW

**Review by Domnicdev — COMMENTED** [review]
Do it clearly.

**Review by Domnicdev — APPROVED** [review]
Do it clearly.

**Review by Domnicdev — APPROVED** [review]
Fine Add it.

**Review by Purushothaman1962 — APPROVED** [review]
Ok fine pull it.

**Comment by ARAVIND472A** [comment]
merged successfully

**Pull request merged**
